apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildkatze-ingress
  namespace: wildkatze-prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  tls:
  - hosts:
    - api.wildkatze.mil
    secretName: wildkatze-tls-secret
  rules:
  - host: api.wildkatze.mil
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wildkatze-api-service
            port:
              number: 80
