apiVersion: v1
kind: Service
metadata:
  name: wildkatze-api-service
  namespace: wildkatze-prod
spec:
  selector:
    app: wildkatze-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadingBalancer
